#!/bin/bash

display=""
if [[ $1 == "west" ]]; then
  if yabai -m window --focus west; then
    exit 0
  fi
  display=$(jq -nr \
      --argjson display "$(yabai -m query --displays --display)" \
      --argjson displays "$(yabai -m query --displays)" \
      '$displays | sort_by(.frame.x + .frame.w / 2, .frame.y + .frame.h / 2) 
      | nth(index(map(select(.id == $display.id))) - 1)
      .index')
elif [[ $1 == "east" ]]; then
  if yabai -m window --focus east; then
    exit 0
  fi
  display=$(jq -nr \
      --argjson display "$(yabai -m query --displays --display)" \
      --argjson displays "$(yabai -m query --displays)" \
      '$displays | sort_by(.frame.x + .frame.w / 2, .frame.y + .frame.h / 2) 
      | reverse 
      | nth(index(map(select(.id == $display.id))) - 1)
      .index')
else
  echo "Invalid option $1"
  exit 1
fi

space=$(jq -nr \
  --argjson spaces "$(yabai -m query --spaces)" \
  --argjson display "$display" \
  '$spaces | .[] | select(.display == $display and ."is-visible") .index'
)

if [[ $1 == "west" ]]; then
  yabai -m window --focus $(yabai -m query --spaces --space $space | jq '."last-window"')
else
  yabai -m window --focus $(yabai -m query --spaces --space $space | jq '."first-window"')
fi

