-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

hl.monitor({
    output = "DP-2",
    mode = "3840x1600@144.00",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@120.00",
    position = "-1920x420",
    scale = "1",
})

local terminal = "wezterm"
local fileManager = "dolphin"
local menu = "anyrun"
local browser = "zen-browser"

hl.env("XCURSOR_SIZE", "20")
hl.env("HYPRCURSOR_SIZE", "20")

hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("GBM_BACKEND", "nvidia-drm")

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1.0 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 5.39,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.79,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    bezier = "easeOutQuint",
    style = "popin 87%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.49,
    bezier = "linear",
    style = "popin 87%",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.73,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.46,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.81,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "easeOutQuint",
    style = "fade",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.5,
    bezier = "linear",
    style = "fade",
})
hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = "2",
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = "3",
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = "4",
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = "5",
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = "6",
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "7",
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "8",
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "9",
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "10",
    monitor = "DP-1",
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

local mainMod = "SUPER"

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal), { description = "Open terminal" })
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.close(), { description = "Close active window" })
hl.bind(mainMod .. " + SHIFT + Space", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating / tiling for the active window" })
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(menu), { description = "Open app launcher" })
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("hyprbind -d | anyrun --plugins libstdin.so --show-results-immediately true"), { description = "Show keybinds" })
hl.bind(mainMod .. " + S", hl.dsp.layout("preselect d"), { description = "Select vertical split" })
hl.bind(mainMod .. " + V", hl.dsp.layout("preselect r"), { description = "Select horizontal split" })

hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }), { description = "Move focus left" })
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }), { description = "Move focus right" })
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }), { description = "Move focus up" })
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }), { description = "Move focus down" })

hl.bind(mainMod .. " + g", hl.dsp.exec_cmd("$(hyprctl activewindow -j | jq '.floating') && hyprctl dispatch cyclenext tiled || hyprctl dispatch cyclenext floating"), { description = "Cycle focus between floating and tiled windows" })

hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }), { description = "Move window left" })
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }), { description = "Move window right" })
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }), { description = "Move window up" })
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }), { description = "Move window down" })
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.center(), { description = "Center the active window" })

hl.bind(mainMod .. " + SHIFT + M", hl.dsp.submap("move"), { description = "Toggle [Move] submap" })
hl.define_submap("move", function()
    hl.bind("h", hl.dsp.window.move({ direction = "l" }), { description = "[Move] Move window left" })
    hl.bind("l", hl.dsp.window.move({ direction = "r" }), { description = "[Move] Move window right" })
    hl.bind("k", hl.dsp.window.move({ direction = "u" }), { description = "[Move] Move window up" })
    hl.bind("j", hl.dsp.window.move({ direction = "d" }), { description = "[Move] Move window down" })

    hl.bind("SHIFT + h", hl.dsp.window.move({ x = -50, y = 0, relative = true }), { repeating = true, description = "[Move] Move floating window left" })
    hl.bind("SHIFT + l", hl.dsp.window.move({ x = 50, y = 0, relative = true }), { repeating = true, description = "[Move] Move floating window right" })
    hl.bind("SHIFT + k", hl.dsp.window.move({ x = 0, y = -50, relative = true }), { repeating = true, description = "[Move] Move floating window up" })
    hl.bind("SHIFT + j", hl.dsp.window.move({ x = 0, y = 50, relative = true }), { repeating = true, description = "[Move] Move floating window down" })

    hl.bind("CTRL + h", hl.dsp.window.move({ x = -200, y = 0, relative = true }), { repeating = true, description = "[Move] Move floating window left (big step)" })
    hl.bind("CTRL + l", hl.dsp.window.move({ x = 200, y = 0, relative = true }), { repeating = true, description = "[Move] Move floating window right (big step)" })
    hl.bind("CTRL + k", hl.dsp.window.move({ x = 0, y = -200, relative = true }), { repeating = true, description = "[Move] Move floating window up (big step)" })
    hl.bind("CTRL + j", hl.dsp.window.move({ x = 0, y = 200, relative = true }), { repeating = true, description = "[Move] Move floating window down (big step)" })

    hl.bind("escape", hl.dsp.submap("reset"), { description = "[Move] Press escape to exit" })
end)

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }), { description = "Switch to Workspace 1" })
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }), { description = "Switch to Workspace 2" })
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }), { description = "Switch to Workspace 3" })
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }), { description = "Switch to Workspace 4" })
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }), { description = "Switch to Workspace 5" })
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }), { description = "Switch to Workspace 6" })
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }), { description = "Switch to Workspace 7" })
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }), { description = "Switch to Workspace 8" })
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }), { description = "Switch to Workspace 9" })
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }), { description = "Switch to Workspace 10" })

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }), { description = "Move to Workspace 1" })
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }), { description = "Move to Workspace 2" })
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }), { description = "Move to Workspace 3" })
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }), { description = "Move to Workspace 4" })
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }), { description = "Move to Workspace 5" })
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }), { description = "Move to Workspace 6" })
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }), { description = "Move to Workspace 7" })
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }), { description = "Move to Workspace 8" })
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }), { description = "Move to Workspace 9" })
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }), { description = "Move to Workspace 10" })

hl.bind(mainMod .. " + P", hl.dsp.workspace.toggle_special("magic"), { description = "Toggle scratchpad" })
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.window.move({ workspace = "special:magic" }), { description = "Move window to scratchpad" })

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace" })
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace" })

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
hl.bind(mainMod .. " + CTRL + h", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { description = "Shrink active window width" })
hl.bind(mainMod .. " + CTRL + l", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { description = "Expand active window width" })
hl.bind(mainMod .. " + CTRL + k", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { description = "Shrink active window height" })
hl.bind(mainMod .. " + CTRL + j", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { description = "Expand active window height" })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.bind(mainMod .. " + backspace", hl.dsp.exec_cmd("makoctl dismiss -a"), { description = "Dismiss notifications" })

hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("hyprshot -m region output --clipboard-only"), { description = "Screenshot region" })

hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd(browser), { description = "Open browser" })
hl.bind(mainMod .. " + CTRL + B", hl.dsp.exec_cmd(browser .. " --blank-window"), { description = "Open blank browser window" })

hl.bind(mainMod .. " + SHIFT + y", hl.dsp.exec_cmd("cliphist list | anyrun --show-results-immediately true --plugins libstdin.so | cliphist decode | wl-copy"), { description = "Open clipboard history" })

hl.bind(mainMod .. " + SHIFT + o", hl.dsp.window.set_prop({ prop = "opaque", value = "toggle", window = "active" }), { description = "Toggle window transparency" })

hl.window_rule({
    name = "workspace10",
    match = {
        class = "^(vesktop|com.github.th_ch.youtube_music)$",
    },
    workspace = "10",
})

hl.window_rule({
    name = "floating-class",
    match = {
        class = "^(Bitwarden|org.kde.dolphin)$",
    },
    size = "1300, 900",
    float = true,
    center = true,
})

hl.window_rule({
    name = "floating-title",
    match = {
        initial_title = "^Vivaldi Settings.*",
    },
    size = "1300, 900",
    float = true,
    center = true,
})

hl.window_rule({
    name = "custom-floating",
    match = {
        initial_class = "^custom-floating$",
    },
    size = "1300, 900",
    float = true,
    center = true,
})

hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_initial_focus = true,
})

hl.config({
    debug = {
        disable_logs = false,
        enable_stdout_logs = true,
    },
    --############################
    --## ENVIRONMENT VARIABLES ###
    --############################
    -- See https://wiki.hyprland.org/Configuring/Environment-variables/
    -- For NVIDIA drivers. Do not remove.
    cursor = {
        no_hardware_cursors = true,
    },
    --####################
    --## LOOK AND FEEL ###
    --####################
    -- Refer to https://wiki.hyprland.org/Configuring/Variables/
    -- https://wiki.hyprland.org/Configuring/Variables/#general
    general = {
        gaps_in = 5,
        gaps_out = {
            top= 15,
            right= 20,
            bottom= 20,
            left= 20,
        },
        border_size = 2,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        col = {
            active_border = { colors = { "rgba(619eb4ee)", "rgba(89b2c6ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#decoration
    decoration = {
        rounding = 10,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 0.9,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
            new_optimizations = true,
            special = true,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#animations
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
    -- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
    -- "Smart gaps" / "No gaps when only"
    -- uncomment all if you wish to use that.
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    dwindle = {
        preserve_split = true, -- You probably want this
        force_split = 2,
    },
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
    ecosystem = {
        no_donation_nag = true,
    },
    --############
    --## INPUT ###
    --############
    -- https://wiki.hyprland.org/Configuring/Variables/#input
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = -0.6, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
    -- Example per-device config
    -- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
    --##################
    --## KEYBINDINGS ###
    --##################
    -- See https://wiki.hyprland.org/Configuring/Keywords/
    -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
    -- bind = $mainMod, M, exit,
    -- bind = $mainMod, E, exec, $fileManager
    -- bind = $mainMod, P, pseudo, # dwindle
    -- Move focus with mainMod + vim keys
    -- Cycle to floating windows
    -- Move window with mainMod + SHIFT + vim keys
    -- Window movement submap.
    -- Switch workspaces with mainMod + [0-9]
    -- Move active window to a workspace with mainMod + SHIFT + [0-9]
    -- Example special workspace (scratchpad)
    -- Scroll through existing workspaces with mainMod + scroll
    -- Move/resize windows with mainMod + LMB/RMB and dragging
    -- Laptop multimedia keys for volume and LCD brightness
    -- Requires playerctl
    -- Notifications
    -- Screenshot
    -- Clipboard
    -- Toggle transparency of active window --- prevents it from going transparent
    -- when out of focus.
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
    -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
    -- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
    -- Discord, messages, and music rules (master layout)
    -- Ignore maximize requests from apps. You'll probably like this.
    -- Fix some dragging issues with XWayland
})

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("mako")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("fcitx5 -d")
end)

